### ISSUE TITLE
[AVM Module Issue]: No variable for storage_tier

### ISSUE THREAD

**Issue by alefteris** [Azure/terraform-azurerm-avm-res-dbforpostgresql-flexibleserver#11]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

The `azurerm_postgresql_flexible_server` resource has a `storage_tier` argument, but the `avm-res-dbforpostgresql-flexibleserver` module doesn't have a variable for it. So the created resource just gets the default value, with no way to increase the IOPS for storage.

**Comment by mbilalamjad** [comment]
Thank you for raising this issue, it has been addressed by #15
