### ISSUE TITLE
[AVM Module Issue]:  Missing creation of `firewall_rule` and output of `AZURE_POSTGRESQL_DATABASE_NAME`

### ISSUE THREAD

**Issue by NanaXiong00** [Azure/terraform-azurerm-avm-res-dbforpostgresql-flexibleserver#20]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Please add creation of `firewall_rule` and output of `AZURE_POSTGRESQL_DATABASE_NAME`.
For example (azd):

- firewall_rule:
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/terraform/core/database/postgresql/postgresql.tf#L50

- Output:
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/terraform/core/database/postgresql/postgresql_output.tf#L1

CC: @rajeshkamal5050 and @mbilalamjad

**Comment by NanaXiong00** [comment]
@mbilalamjad Do you have any questions about this issue? If not, we will start trying to fix it.
CC: @rajeshkamal5050

**Comment by v-xuto** [comment]
@mbilalamjad We have created a PR https://github.com/Azure/terraform-azurerm-avm-res-dbforpostgresql-flexibleserver/pull/25 for this issue, please review. Thanks.
