### ISSUE TITLE
[AVM Module Issue]: Required version of azurerm is wrong

### ISSUE THREAD

**Issue by taustgen** [Azure/terraform-azurerm-avm-res-dbforpostgresql-flexibleserver#9]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

Readme shows required version of azure rm as [azurerm](https://github.com/Azure/terraform-azurerm-avm-res-dbforpostgresql-flexibleserver#requirement_azurerm) (~> 3.71)

Needs to be >= 3.105.0 to successfully run. Prior to that version  `public_network_access_enabled` is not a configurable attribute.

```

│ Error: Value for unconfigurable attribute
│
│   with module.postgres.azurerm_postgresql_flexible_server.this,
│   on .terraform/modules/postgres/main.tf line 14, in resource "azurerm_postgresql_flexible_server" "this":
│   14:   public_network_access_enabled     = var.public_network_access_enabled
│
│ Can't configure a value for "public_network_access_enabled": its value will
│ be decided automatically based on the result of applying this
│ configuration.
````

**Comment by mbilalamjad** [comment]
Thank you for raising this issue, it has been addressed by #15
